#!/bin/sh

[ -z $1 ] && {
    ocamllex lexer.mll   # generates lexer.ml
    ocamlyacc parser.mly # generates parser.ml & parser.mli
    for f in parser.mli lexer.ml parser.ml calc.ml; do
        ocamlc -c "$f"
    done
    ocamlc -o calc lexer.cmo parser.cmo calc.cmo
}

[ "$1" = clean ] && {
    rm -v -- calc *.cmo *.cmi *.mli lexer.ml parser.ml
}
